
name: Pipeline for Cookbok app - exam 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-unit-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install packages
      run: npm install 
    - name: Start app on localhost:8080 
      run: npm run start &
    - name: Run unit tests 
      run: npm run test:unit
    - name: Show Softuni username - ssllaavv
      run: echo "ssllaavv"


  UI-tests:

    runs-on: ubuntu-latest
    needs: build-and-unit-tests

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install packages
      run: npm install 
    - name: Install Playwright Browsers
      run:  npx playwright install  
    - name: Start app on localhost:8080 
      run: npm run start &
    - name: Run UI tests 
      run: npm run test:ui
   

